### ISSUE TITLE
Legacy version blackberry OS Version: `qnx Android 4.3-18` also available for testing.

### ISSUE THREAD

**Issue by fortunewalla** [TeamNewPipe/NewPipe-legacy#10]
- [Y ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ Y] I checked if the issue/feature exists in the latest version.
- [Y ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Summary: I have BB z30 device `qnx Android 4.3-18`. Was using NewPipe `0v0.14.2` but yesterday stopped playing videos. Found @friendlyanon NewPipeLegacy version installed from fdroid. Works!. Thanks for much for maintaining legacy version. Can do future testing if you want.

---------------------------
I have a Blackberry z30. I used to use SuperTube, a native BB YouTube application but it stopped working due to decrypt error. I used NewPipe by installing the APK. It works very well with all the features including background play. The OS Version gives: `qnx Android 4.3-18`.

I was using NewPipe `0v0.14.2`. Yesterday the decrypt error started and I came across your Legacy version through https://github.com/TeamNewPipe/NewPipe/issues/2259  while searching for a solution. I never knew NewPipe stopped supported `4.1-4.3`

I'm so glad that @friendlyanon is maintaining a legacy version. It works on the Blackberry. Hope the legacy project will continue for a long time. I can be available if you want to test on blackberry device. Thanks a lot!

**Comment by friendlyanon** [comment]
Thanks, I'll let you know if there is ever a need for additional testers.
