### ISSUE TITLE
Please make a new release to update NewPipeExtractor

### ISSUE THREAD

**Issue by danieru98** [TeamNewPipe/NewPipe-legacy#11]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I know merging all the changes in NewPipe 0.16.2 could take some time, but for now a new release be made just to update NewPipeExtractor to fix this bug https://github.com/TeamNewPipe/NewPipeExtractor/pull/163

**Comment by friendlyanon** [comment]
Updated to latest upstream and tested on my phone, didn't find any issues.

**Comment by danieru98** [comment]
That was fast! Thank you very much

**Comment by friendlyanon** [comment]
No problem.  
The merge from upstream was painless, so it was done quickly, but I have very little free time for sideprojects due to uni and my summer webdev job taking almost all of it :(
