### ISSUE TITLE
Home feed doesn't load more than 10 videos

### ISSUE THREAD

**Issue by moshpirit** [TeamNewPipe/NewPipe-legacy#15]
Basically this:

![](https://i.imgur.com/qmwxZsG.png)

This is NewPipe Legacy 0.16.2 on Android 4.1.1 with a stable WiFi connection.

**Comment by friendlyanon** [comment]
If the problem persists in the latest version, feel free to reopen the issue.

**Comment by B0pol** [comment]
Reopen this. It still happens, and here is the upstream issue: TeamNewPipe/NewPipe#1974
