### ISSUE TITLE
Newpipe: Content Unavailable

### ISSUE THREAD

**Issue by acjones8** [TeamNewPipe/NewPipe-legacy#17]
- [X ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ X] I checked if the issue/feature exists in the latest version.
- [X ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

On the most recent version of Newpipe-Legacy, I've noticed that any video I try to play now just shows "Content unavailable" in the place of where there used to be the video frame. This effectively makes the app unusable, as it can no longer be used to watch any videos. It doesn't crash so I don't think there's a crash dump to upload, but I'm happy to assist with whatever information could be helpful.

**Comment by vectra699** [comment]
the same for me

**Comment by acjones8** [comment]
Seems to have been a problem with the YouTube API. I tried out the new release that came out a few days ago, and it works fine once again!

**Comment by vectra699** [comment]
Hello,
All is ok for me now.
thks.
