### ISSUE TITLE
Replace StandardCharsets

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe-legacy#23]
Hey,
I wanted to remind you that we use [StandardCharsets](https://developer.android.com/reference/java/nio/charset/StandardCharsets) in the downloader. StandardCharsets have been introduced with KitKat. You need to replace this with `"utf-8"` to not get crashes.

**Comment by friendlyanon** [comment]
This has been addressed. Thank you for notifying!
