### ISSUE TITLE
A Display Bug

### ISSUE THREAD

**Issue by franklinbill** [TeamNewPipe/NewPipe-legacy#24]
Dear developer
In the process of using, I found a bug in layout / display. There is text occlusion at the top of the sidebar of the application. The lower part of "Legacy" in "Newpipe Legacy" is blocked, which may be an adaptation problem.
App version is 0.18.6, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![image](https://user-images.githubusercontent.com/18572115/78906568-1a2ac780-7ab2-11ea-997d-aeacab32a204.png)

**Comment by B0pol** [comment]
It has been fixed with upstream version 0.19.2 (search drawer [in this changelog](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.19.2)).
