### ISSUE TITLE
[Feature request] Support for Fire OS 7.5.1

### ISSUE THREAD

**Issue by kickshuff** [TeamNewPipe/NewPipe-legacy#25]
I like that Newpipe released a legacy app, unfortunately it doesn't cover my Kindle and Motorola phone which both currently run a version of ice cream sandwich
My kindle is as up to date as it can be, version 7.5.1 which is based on android 4.0.3 ICS
My Motorola Atrix 2 also runs 4.0.3 ICS
I don't know the probability for compatibility, but it doesn't hurt to request. Who knows, maybe it could be picked up. Thanks, J.
- [ y] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ y] I checked if the issue/feature exists in the latest version.
- [ n] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by B0pol** [comment]
NewPipe isn't supporting and won't support versions under 4.4 KitKat
And I've seen you've opened an issue in NewPipe legacy, which supports NewPipe for older versions
I'm closing in favor of https://github.com/TeamNewPipe/NewPipe-legacy/issues/25

**Comment by kickshuff** [comment]
> @malekairmaroc7 Here is my latest version that fix Resolution Spinner so you can choose it to play
> 
> You can download at: https://drive.google.com/open?id=1_9roWosYM_sf-idB8wJ3ELUJjW-Px2WO

Well, I guess someone did try! I am currently testing it out on my Kindle. Live streams seam to quit after a few seconds, but normal uploaded content plays flawlessly (for now). I figure I can close this thread until something doesn't work anymore. Thanks, J.
