### ISSUE TITLE
Export Newpipe database to Newpipe Legacy

### ISSUE THREAD

**Issue by SpazMahTazz** [TeamNewPipe/NewPipe-legacy#26]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

This is not a bug but just a compatibility query.
I tried exporting my database from Newpipe v0.19.3 and import them to Newpipe Legacy v0.18.6 but they don't import anymore. The last database I tried to do this with worked which is dated 16/02/2020 but I don't know what versions both of them were on at the time.
Do you think it's possible to add this again? I primarily use Newpipe on my main device and occasionally use Newpipe Legacy on my other device but when I use Legacy I'd like to transfer my current settings from my main device.

**Comment by friendlyanon** [comment]
Upstream has been merged.

**Comment by SpazMahTazz** [comment]
Hi,
This issue is happening again. The error "No valid ZIP file" pops up when I try exporting my Newpipe v0.19.5 database to Newpipe Legacy v0.19.5.
