### ISSUE TITLE
NewPipe-legacy 0.18.6 crashes when opening youtube video streams 

### ISSUE THREAD

**Issue by NetrunnerXP** [TeamNewPipe/NewPipe-legacy#27]
Hello NewPipe Team,

Sorry for posting a crash in here. Unfortunately my device is not able to send the automatic reports. I'm using NewPipe-legacy on my car's head-unit (Android 4.2.2 / no email client). Unfortunately since a few days since a few days NewPipe crashes when opening YouTube videos. When you e.g. choose a title in the search, the following screen crashes with an URL parse exception. It started intermittently but now seems to impacts almost all video files.

Is this an issue with has been addressed with the latest 0.19.x release of the main application, or is this something completely new? Let me know if I should provide a "screenshot".

Thank you in advance for taking a look.
Thanks,
Alex

**Comment by TobiGr** [comment]
Will be fixed in NewPipe version 0.19.4 which is going to be released later today. @friendlyanon Needs to update the legacy version after that.
See TeamNewPipe/NewPipeExtractor#333 for the fix

**Comment by friendlyanon** [comment]
Upstream changes have been merged, tested (mostly) and released.
