### ISSUE TITLE
Update notifications are (also?) notifying about NewPipe updates, not (only?) NewPipeLegacy.

### ISSUE THREAD

**Issue by r-salvaterra** [TeamNewPipe/NewPipe-legacy#28]
Basically, $subject. I just started NewPipeLegacy on an old phone I have and the app notified me about an update to version 0.19.5.

### Version

- 0.19.4

### Steps to reproduce the bug
1. Start NewPipeLegacy with update notifications enabled after a new release of NewPipe.

### Expected behavior

No update notification should appear.

### Actual behaviour

NewPipeLegacy notifies about NewPipe app updates.

**Comment by friendlyanon** [comment]
I messed up, apologies.

It was a big merge from upstream and I missed setting the update checker to check legacy versions.
