### ISSUE TITLE
Fix F-Droid build

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe-legacy#29]
See https://f-droid.org/wiki/page/org.schabi.newpipelegacy/lastbuild_70. To fix, just downgrade to a lower Gradle version, like the one used by non-Legacy NewPipe.

**Comment by friendlyanon** [comment]
Apologies, I updated Android Studio and it asked me to upgrade Gradle as well.

I didn't think that would break anything.

**Comment by licaon-kter** [comment]
Umm the issue is that You have DOS endlines in https://github.com/TeamNewPipe/NewPipe-legacy/blob/master/gradle/wrapper/gradle-wrapper.properties not 6.1.1 (which is available in F-Droid FYI)
