### ISSUE TITLE
Fix F-Droid build (2)

### ISSUE THREAD

**Issue by mnlmnl** [TeamNewPipe/NewPipe-legacy#32]
>Umm the issue is that you have DOS endlines _(the red `^M`)_ in https://github.com/TeamNewPipe/NewPipe-legacy/blob/master/gradle/wrapper/gradle-wrapper.properties not 6.1.1 _(which is available in F-Droid FYI)_

_Originally posted by @licaon-kter in https://github.com/TeamNewPipe/NewPipe-legacy/issues/29#issuecomment-641407918_

Apparently this is the issue, it's a matter of just replacing those for UNIX line endings.

**Comment by wb9688** [comment]
@friendlyanon: Did you fix this for v0.19.8?

**Comment by friendlyanon** [comment]
Ah yes, I changed the line endings to LF and forgot to close this.  
I don't even know how the line ending ended up becoming CR only.
