### ISSUE TITLE
Expand fdroid app description about differences to the old Newpipe app

### ISSUE THREAD

**Issue by tusch001** [TeamNewPipe/NewPipe-legacy#4]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi

As of today there are two new releases on fdroid, Newpipe 16.0 and this new Newpipe Legacy 15.1.
To the user they look the same, use the same database and seem to be developed by the same team. I don't know the differences and can't decide which app to keep. Please add some information for the normal user, I would suggest to the fdroid app description. (Or here?)
Thx

**Comment by theScrabi** [comment]
Yes at least the description had to be changed in order to clarify why newpipe legecy exist and for what it is used for.

**Comment by friendlyanon** [comment]
Hopefully [this](https://gitlab.com/fdroid/fdroiddata/merge_requests/4563) will address the issue.  
The fdroid linter prevents me from stating `Android 4.x` so I had to go with `OS versions 4.x`.

**Comment by friendlyanon** [comment]
The fdroid description has been made more clear and with the new icons from https://github.com/TeamNewPipe/NewPipe-legacy/commit/77c947dd8ddf7b6f6a02c648f210e030707698f9 I can consider this issue resolved.

**Comment by OffifialMITX** [comment]
So, Newpipe Legacy is basically the same, but supports older devices? Am I getting this right?

**Comment by friendlyanon** [comment]
Yes, **for now** the two versions do not diverge, only in the icon and name. When I have the time I will reimplement the old player that will make 4.0.x versions supported as well, but as of now university is keeping me busier than I'd like it.

**Comment by OffifialMITX** [comment]
So, is this really an actual issue that this many devices are below 4.6? Like, I'm not criticising your work, I'm just surprized, since the oldest functioning device I have is 5.1 which has been in use for 4-5 years and I really took care of it. Also the F-Droid description does not give any hint of why legacy exists. Not that I'd see that.
