### ISSUE TITLE
Pause/Play symbol issues

### ISSUE THREAD

**Issue by LukasThyWalls** [TeamNewPipe/NewPipe-legacy#41]
### Version

- Newpipe Legacy 0.19.8
- Tablet is Arnova WM8850-mid, with Android 4.1.1 JB Ver1.3.5-20130322.068719. The screen width is 1024x600.

### Steps to reproduce the bug

Playing any video, the pause/play button has a strange symbol behind. It also is unresponsive unless you tap in the border of the box of the button, if you tap in the center, it does nothing.

### Expected behavior

It works as always, you can play and pause without issue.

### Actual behaviour

Button is unresponsive unless you press the border of the box.

### Screenshots/Screen recordings

This is like i see when the pause symbol is shown. With the play symbol is behind, but you almost can't see it, but is there behind.
![Screenshot_2020-10-20-19-08-22](https://user-images.githubusercontent.com/1467366/96624140-a4c76b80-130c-11eb-8505-a721f9e1a8c6.png)

This is a screenshot of the symbol behind along i managed to do.
![Screenshot_2020-10-20-19-11-52](https://user-images.githubusercontent.com/1467366/96624811-9463c080-130d-11eb-92c9-d25102e116e4.png)

The red part is the aprox. responsive part of the button, if you press in the middle, it does nothing (as pause or as play) but you can push the red part and it does the job.
![Screenshot_2020-10-20-19-11-37](https://user-images.githubusercontent.com/1467366/96624826-9c236500-130d-11eb-8f83-b7873861ad1e.png)

### Logs

If needed...

**Comment by drogga** [comment]
Fixed !
@friendlyanon You can close this (and delete my comment).
