### ISSUE TITLE
NewPipe-legacy 0.19.9 not have apk on release page

### ISSUE THREAD

**Issue by Domiuns** [TeamNewPipe/NewPipe-legacy#43]
Hi @TobiGr sorry for disturbing, [NewPipe-legacy 0.19.9](https://github.com/TeamNewPipe/NewPipe-legacy/releases/tag/0.19.9) not have apk on release page, can you upload apk ?
I have remove my name from the tester newpipe (normal version) because my android 4.4 custom rom is bad.

**Comment by friendlyanon** [comment]
I am in the process of merging from upstream, building, testing, pulling in #31, building the testing again.

0.20.1 will be released shortly.
