### ISSUE TITLE
With some playlists, it doesn't advance to the next video

### ISSUE THREAD

**Issue by LukasThyWalls** [TeamNewPipe/NewPipe-legacy#54]
### Checklist

- [x] I am using the latest version - 0.20.2 NewPipe Legacy 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

- I have this playlist bookmarked https://www.youtube.com/playlist?list=PLFTcWm5cJeAh7raw0shnQGHQ5OxemdEIT
- In any video from the playlist, i choose to play it in background. 
- It takes some time, but it plays normally until it ends.
- It should be reproducing the next video in playlist but...

### Actual behaviour

- ... It doesn't play. It keeps loading indefinitely.
- In fact, you can play any other video. They don't load.
- You need to exit and swip out Newpipe Legacy and enter again to play any other video.

### Expected behavior

- When a video ends in a playlist, it should be playing the next one in the playlist.
- In fact, with a new created playlist with three short videos (not a one searched and bookmarked), it pass from the next one like normal.

### Logs

This is the log from Newpipe in aLogCat, during the bug with the mentioned playlist:
[alogcat.2020-12-11-21-32-18+0100_Bug.txt](https://github.com/TeamNewPipe/NewPipe-legacy/files/5681970/alogcat.2020-12-11-21-32-18%2B0100_Bug.txt)

Also, this is the log when using that short playlist which doesn't do that problem:
[alogcat.2020-12-11-21-17-51+0100_noBug.txt](https://github.com/TeamNewPipe/NewPipe-legacy/files/5681971/alogcat.2020-12-11-21-17-51%2B0100_noBug.txt)

### Device info

 - Android version/Custom ROM version: 4.1.1 JB Ver1.3.5-20130322.065719
 - Device model: Arnova 10d G3 (WonderMedia WM8850-mid)

**Comment by friendlyanon** [comment]
Couldn't reproduce. It looks like an OOM bug from a reactive flow. Probably fixed in upstream.
