### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jonapaniagua** [TeamNewPipe/NewPipe-legacy#60]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by drogga** [comment]
...and do you mind sharing what's the actual bug, because you didn't provide any crash log, nor details !?
Please edit your OP, or close this,currently pointless issue. Thanks.

**Comment by friendlyanon** [comment]
Reopen when you actually have something to report.
