### ISSUE TITLE
Trying to import a.json file from youtube subscription 

### ISSUE THREAD

**Issue by ThoLorax503** [TeamNewPipe/NewPipe-legacy#61]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version: Android 11/CalyxOS 2.1.0
 - Device model: Pixel 4a

**Comment by drogga** [comment]
...and do you mind sharing what's the actual bug ?, because you didn't provide any crash log, nor details, but only a subject title and unfilled 'issue' template...

Please edit your OP, or close this currently (kind of) pointless\useless 'issue'.
Thanks.
