### ISSUE TITLE
[FEATURE] Fallback mode on decryption errors

### ISSUE THREAD

**Issue by konkor** [TeamNewPipe/NewPipe-legacy#8]
It is nice to have Fallback Mode on extractor decryption errors to open requested videos in WebView as embedded video frame or/end external web browser without extra bloatware on main YouTube page. You know Legacy devices is limited by resources.

Also nice to have ability to share that embedded video link not main at least.

I'm just happy to have local bookmarks/search for yt without any other providers. Keep it lite for legacy.

Thank you very much!

**Comment by konkor** [comment]
Now I can open video links by context menu and share it via browser but it very bloated and laggy.

**Comment by theScrabi** [comment]
Nah. We rather work on faster ota updates ;D

**Comment by konkor** [comment]
OMG LoL. Okay.

Could you add Share embedded option at least for emergency situations at least???
